name: Test Docker build
on:
  pull_request:
    branches: ["main", "release-*"]
permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64] # linux/arm64 is too slow on GitHub Actions.
        file: [Dockerfile, k8scache.Dockerfile]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./${{ matrix.file }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}